(function() {
  'use strict';

  var gulp = require('gulp');
  var runSequence = require('run-sequence');
  var plumber = require('gulp-plumber');

  var ENV = require('./get-env.js');

  var paths = {
    root: './',
    less: './less/',
    env: './components/env/env.json',
    components: './components/',
  };

  /**
   * Build
   */

  gulp.task('generate-env-module', function() {
    var ngConstant = require('gulp-ng-constant');

    // This task builds the angular ENV constant
    // Constants defined here extend the constants in env.json
    var template =
      "/**\n" +
      " DO NOT EDIT\n" +
      " Generated by gulp during build.\n" +
      " Edit the generate-env-module task.\n" +
      " */\n" +
      "(function EnvironmentConstantIIFE() {\n" +
      "    'use strict';\n\n" +
      "    angular.module('App.env', [])\n" +
      "        .constant('ENV', {\n" +
      "<% constants.forEach(function(constant) { %>" +
      "            '<%- constant.name %>': <%= constant.value %>,\n" +
      "<%});%>" +
      "        });\n" +
      "}());";


    return gulp.src(paths.env)
      .pipe(ngConstant({
        name: 'foo',
        space: 4,
        template: template,
        constants: {
          KINVEY_APP_KEY: ENV.KINVEY_APP_KEY,
          KINVEY_APP_SECRET: ENV.KINVEY_APP_SECRET,
          STRIPE_PUBLISHABLE_KEY: ENV.STRIPE_PUBLISHABLE_KEY
        }
      }))
      .pipe(gulp.dest(paths.components + 'env'));
  });

  gulp.task('less', function() {
    var autoprefixer = require('gulp-autoprefixer');
    var less = require('gulp-less');

    return gulp.src([
      paths.less + 'app.less'
    ])
      .pipe(plumber(function onError(err) {
          console.log(err.message);
          this.emit('end');
        }
      ))
      .pipe(less())
      .pipe(autoprefixer())
      .pipe(gulp.dest('.'));
  });


  /**
   * Watch
   */
  gulp.task('watch', function() {
    gulp.watch([paths.root + '**/*.less'], ['less']);
  });


  /**
   * Build
   */
  gulp.task('build', function(cb) {
    runSequence(
      [
        'generate-env-module',
        'less',
      ],
      cb
    )
  });

  gulp.task('heroku:production', function(cb) {
    runSequence(
      [
        'build'
      ],
      cb
    )
  });


  /**
   * Default
   */
  gulp.task('default', [
    'build',
    'watch',
  ]);

}());
