/**
 DO NOT EDIT
 Generated by gulp during build.
 Edit the generate-env-module task.
 */
(function EnvironmentConstantIIFE() {
    'use strict';

    angular.module('App.env', [])
        .constant('ENV', {
            'TSC_KINVEY_APP_KEY': "kid_-1JJaW_I3",
            'TSC_KINVEY_APP_SECRET': "b0b1b6202a0e4124aa20050551348750",
        });
}());