/**
 DO NOT EDIT
 Generated by gulp during build.
 Edit the generate-env-module task.
 */
(function ppEnvironmentConstantModule() {
    'use strict';

    angular.module('App.env', [])
        .constant('ENV', {
            'TSC_KINVEY_APP_KEY': "kid_-1JJaW_I3",
            'TSC_KINVEY_APP_SECRET': "e8c3308a7c5648cbb76e97c8abfc3179",
        });
}());